- hosts: localhost
  vars:
    - ansible_python_interpreter: python
  vars_files:
    - vars.yml
#  vars_prompt:
#    do_name: "Servername to destroy"
#    do_dns: "DNS name to delete"
  tasks:
    - digital_ocean: >
        state=present
        command=ssh
        name=my_droplet
        size_id=6
        region_id=5
        image_id=9801950
        wait_timeout=500
      register: my_droplet
    - debug: msg="ID is {{ my_droplet.droplet.id }}"
    - debug: msg="IP is {{ my_droplet.droplet.ip_address }}"
